webserver:
  enable: true
  api: true
  address: 0.0.0.0
  port: 1234
  webroot: ./webroot
database:
  path: ./test.db
dnsserver:
  enable: true
  domain: onffhb.de
  ipv6prefix: fd2f:5119:f2c::/64
  ipv4prefix: 10.196.0.0/17
